/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/slider/slider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { View, Slider } = scope;
  return (
<View style={{ width: 64 }}>
  <Slider accessibilityLabel="Volume" defaultValue={65} min={0} max={100} />
</View>
  );
}
