/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/slider/slider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Slider, Column } = scope;
  return (
<Column snug>
  <Slider narrow defaultValue={40}>Narrow (240px)</Slider>
  <Slider defaultValue={40}>Standard (320px)</Slider>
  <Slider wide defaultValue={40}>Wide (480px)</Slider>
  <Slider block defaultValue={40}>Block (fills the container)</Slider>
</Column>
  );
}
