/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/slider/slider.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Slider } = scope;
  return (
<Slider accessibilityLabel="Playback speed" defaultValue={6} min={0} max={10} step={2} />
  );
}
