/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/dialog/dialog.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Dialog, Input, Typography, Row, Column } = scope;
  return (
<Dialog open large>
  <Column relaxed>
    <Column tight>
      <Typography lead semibold>Edit profile</Typography>
      <Typography>Update how your name and email appear to teammates.</Typography>
    </Column>
    <Column relaxed>
      <Input block label="Name" defaultValue="Ada Lovelace" />
      <Input block label="Email" defaultValue="ada@example.com" />
    </Column>
    <Row end snug alignCenter>
      <Button outline small>Cancel</Button>
      <Button primary small>Save changes</Button>
    </Row>
  </Column>
</Dialog>
  );
}
