/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/organisms/dialog/dialog.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Button, Dialog, Typography, Row, Column } = scope;
  return (
<Dialog open medium>
  <Column relaxed>
    <Column tight>
      <Typography lead semibold>Unsaved changes</Typography>
      <Typography>You have edits that are not saved.</Typography>
    </Column>
    <Row end snug alignCenter wrap>
      <Button ghost small>Discard</Button>
      <Button outline small>Keep editing</Button>
      <Button primary small>Save</Button>
    </Row>
  </Column>
</Dialog>
  );
}
