/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/listbox/listbox.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Listbox } = scope;
  return (
<Listbox
  items={[
    { label: "Rachel Chen", detail: "rachel@acme.io", selected: true },
    { label: "Ada Lovelace", detail: "ada@acme.io", selected: false },
    { label: "Kevin Turner", detail: "kevin@acme.io", selected: false },
    { label: "Linus Berg", detail: "linus@acme.io", selected: false }
  ]}
  bordered
/>
  );
}
