/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/listbox/listbox.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Listbox, Column } = scope;
  return (
<Column snug>
  <Listbox narrow bordered items={[{ label: "Narrow (240px)", selected: true }, { label: "Frontend" }]} />
  <Listbox bordered items={[{ label: "Standard (320px)", selected: true }, { label: "Frontend" }]} />
  <Listbox wide bordered items={[{ label: "Wide (480px)", selected: true }, { label: "Frontend" }]} />
  <Listbox block bordered items={[{ label: "Block (fills the container)", selected: true }, { label: "Frontend" }]} />
</Column>
  );
}
