/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/listbox/listbox.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Listbox } = scope;
  return (
<Listbox
  items={[
    { label: "Backend", selected: true },
    { label: "Frontend", selected: false },
    { label: "Design", selected: false },
    { label: "Platform", selected: false },
    { label: "Security", selected: false }
  ]}
  bordered
  disabled
/>
  );
}
