/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/autocomplete/autocomplete.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Autocomplete } = scope;
  return (
<Autocomplete
  options={[
    "Ada Lovelace",
    "Grace Hopper",
    "Kira Tanaka",
    "Liang Bao",
    "Marcus Allen",
    "Noor Park",
    "Rachel Chen"
  ]}
  label="Assigned to"
  required
  placeholder="Search a person…"
/>
  );
}
