/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/autocomplete/autocomplete.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Stateful, Autocomplete, Typography, Column } = scope;
  return (
<Stateful initial="Grace Hopper">
  {(value, setValue) => (
    <Column snug>
      <Autocomplete
        label="Assigned to"
        options={["Ada Lovelace", "Grace Hopper", "Kira Tanaka"]}
        value={value}
        onValueChange={setValue}
      />
      <Typography muted>{value === "" ? "No assignee" : `Selected: ${value}`}</Typography>
    </Column>
  )}
</Stateful>
  );
}
