/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/autocomplete/autocomplete.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Autocomplete, Column } = scope;
  return (
<Column snug>
  <Autocomplete narrow options={["Ada Lovelace", "Grace Hopper"]} placeholder="Narrow (240px)" />
  <Autocomplete options={["Ada Lovelace", "Grace Hopper"]} placeholder="Standard (320px)" />
  <Autocomplete wide options={["Ada Lovelace", "Grace Hopper"]} placeholder="Wide (480px)" />
  <Autocomplete block options={["Ada Lovelace", "Grace Hopper"]} placeholder="Block (fills the container)" />
</Column>
  );
}
