/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/select/select.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Select, Column } = scope;
  return (
<Column snug>
  <Select narrow options={["Small", "Medium", "Large"]} placeholder="Narrow (240px)" />
  <Select options={["Small", "Medium", "Large"]} placeholder="Standard (320px)" />
  <Select wide options={["Small", "Medium", "Large"]} placeholder="Wide (480px)" />
  <Select block options={["Small", "Medium", "Large"]} placeholder="Block (fills the container)" />
</Column>
  );
}
