/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/textarea/textarea.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Textarea, Column } = scope;
  return (
<Column snug>
  <Textarea narrow rows={2} placeholder="Narrow (240px)" />
  <Textarea rows={2} placeholder="Standard (320px)" />
  <Textarea wide rows={2} placeholder="Wide (480px)" />
  <Textarea block rows={2} placeholder="Block (fills the container)" />
</Column>
  );
}
