/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/progress/progress.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Progress, Column } = scope;
  return (
<Column snug>
  <Progress narrow value={0.6}>Narrow (240px)</Progress>
  <Progress value={0.6}>Standard (320px)</Progress>
  <Progress wide value={0.6}>Wide (480px)</Progress>
  <Progress block value={0.6}>Block (fills the container)</Progress>
</Column>
  );
}
