/* @generated by tools/docgen. DO NOT EDIT. Run `bun run docs:gen`. */
// Source: src/atoms/progress/progress.md
import type { ExampleScope } from "../../../scope";

export default function Example(scope: ExampleScope) {
  const { Progress } = scope;
  return (
<Progress accessibilityLabel="Uploading files" value={0.4} />
  );
}
